language: cpp
before_install: 
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install mysql-client libmysqlclient-dev sqlite3 libsqlite3-dev libjson0 libjson0-dev uuid-dev liburiparser-dev
  - mysql -e "create database IF NOT EXISTS test;" -uroot    
before_script: 
  - git submodule update --init --recursive
  - autoreconf --recursive -if
install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8 
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --config g++

